---
# Manage Galaxy download

- name: Check for Galaxy download receipt
  stat:
    path: "{{ galaxy_server_dir }}/{{ galaxy_commit_id }}_receipt"
  register: download_receipt

- name: Create Galaxy server directory
  file:
    path: "{{ galaxy_server_dir }}"
    state: directory

- name: Install current version of Galaxy
  unarchive:
    src: "{{ galaxy_download_url }}"
    dest: "{{ galaxy_server_dir }}"
    extra_opts: --strip-components=1
    remote_src: yes
  when: not download_receipt.stat.exists

- name: Create Galaxy download receipt
  file:
    path: "{{ galaxy_server_dir }}/{{ galaxy_commit_id }}_receipt"
    state: touch
  when: not download_receipt.stat.exists

- name: Include virtualenv setup tasks
  include_tasks: virtualenv.yml

- name: Remove orphaned .pyc files and compile bytecode
  script: makepyc.py {{ galaxy_server_dir }}/lib
  environment:
    PATH: "{{ galaxy_venv_dir }}/bin"
