---
# main tasks file for galaxyproject.galaxy

# Deploy a Galaxy server
#   https://wiki.galaxyproject.org/

- name: Include clone tasks
  include_tasks: clone.yml
  when: galaxy_manage_clone
  tags:
    - galaxy_manage_clone

- name: Include download tasks
  include_tasks: download.yml
  when: not galaxy_manage_clone and galaxy_manage_download
  tags:
    - galaxy_manage_download

- name: Build client
  include_tasks: build_client.yml
  when: (galaxy_manage_clone and current_repo_state.before | default(-1) != galaxy_commit_id) or (galaxy_manage_download and not download_receipt.stat.exists)
  tags:
   - galaxy_build_client

- name: Include static config setup tasks
  include_tasks: static_setup.yml
  when: galaxy_manage_static_setup
  tags:
   - galaxy_config_files

- name: Include dependency setup tasks
  include_tasks: dependencies.yml
  when: galaxy_fetch_dependencies

- name: Include mutable config setup tasks
  include_tasks: mutable_setup.yml
  when: galaxy_manage_mutable_setup

- name: Include database management tasks
  include_tasks: database.yml
  when: galaxy_manage_database

- name: Include error document setup tasks
  include_tasks: errordocs.yml
  when: galaxy_manage_errordocs
