---
# Instantiate mutable config files

- name: Mutable config setup
  block:

    - name: Ensure Galaxy version is set
      include_tasks: _inc_galaxy_version.yml
      when: __galaxy_major_version is undefined

    - name: Create mutable configuration file directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ galaxy_mutable_config_dir }}"
        - "{{ galaxy_tool_dependency_dir }}"

    - name: Instantiate mutable configuration files
      command: cp {{ item.src }} {{ item.dest }}
      args:
        creates: "{{ item.dest }}"
      with_items: "{{ galaxy_mutable_configs }}"
      when: __galaxy_major_version is version('19.09', '<')

    - name: Template mutable configuration files
      template:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          force: no # Will not template, if already exists. https://docs.ansible.com/ansible/latest/modules/template_module.html
      with_items: "{{ galaxy_mutable_config_templates }}"

  remote_user: "{{ galaxy_remote_users.galaxy | default(__galaxy_remote_user) }}"
  become: "{{ true if galaxy_become_users.galaxy is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.galaxy | default(__galaxy_become_user) }}"
