---
# Manage static Galaxy configuration files

- name: Static config setup
  block:

    - name: Create Galaxy config and shed tools directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ galaxy_config_dir }}"
        - "{{ galaxy_shed_tools_dir }}"

    - name: Install additional Galaxy config files (static)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        backup: "{{ galaxy_backup_configfiles }}"
      with_items: "{{ galaxy_config_files }}"

    - name: Install additional Galaxy config files (template)
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        backup: "{{ galaxy_backup_configfiles }}"
      with_items: "{{ galaxy_config_templates }}"

    - name: Create Galaxy configuration file
      template:
        src: "{{ galaxy_config_file_template }}"
        dest: "{{ galaxy_config_file }}"
        backup: "{{ galaxy_backup_configfiles }}"
      notify:
        - restart galaxy

  remote_user: "{{ galaxy_remote_users.privsep | default(omit) }}"
  become: "{{ true if galaxy_become_users.privsep is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.privsep | default(ansible_user_id) }}"
